import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NewsProvider } from "../../context/NewsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <NewsProvider> */}
          {children}
        {/* </NewsProvider> */}
        </body>
    </html>

  );
}
