import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NewsProvider } from "../../context/NewsContext";
// import { GoogleAnalytics } from '@next/third-parties/google'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "perpenka",
  description: "Generated by create next app",
  icons: {icon: "/img/logofix.png"}
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <NewsProvider>
          <html lang="en">
            <body className={inter.className}>
                {children}
              </body>
              {/* <GoogleAnalytics gaId="G-FQ6V4E5T2S" /> */}
          </html>
      </NewsProvider>

  );
}