import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { NewsProvider } from "../../../context/NewsContext";
import Navbar from "../../../components/navbar";
import Footer from "../../../components/footer";
// import { GoogleAnalytics } from '@next/third-parties/google'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "perpenka",
  description: "Generated by create next app",
  icons: {icon: "/img/logofix.png"}
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      // <NewsProvider>
      //     <html lang="en">
            <main className={`${inter.className} bg-fixed bg-cover bg-[url("../../public/img/alambg.png")]`}>
            <Navbar isGray={false} />
            {children}
            <Footer />
            </main>
      //     </html>
      // </NewsProvider>

  );
}
